name: 🚀 Build Flutter Web & Deploy to GitHub

# Precisamos de permissão de escrita para fazer o push via GITHUB_TOKEN
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true    # mantém o GITHUB_TOKEN configurado

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web (no tree-shake icons)
        run: flutter build web --release --no-tree-shake-icons

      - name: Commit built web assets
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Força a inclusão de tudo em build/web mesmo estando no .gitignore
          git add -f build/web
          # Comita apenas se houver algo novo
          git diff --cached --quiet || git commit -m "CI: Atualiza build web (Flutter)"
          git push
